// CLI command implementations

use crate::cli::output::{success, error, cyan, green, yellow, dim};
use anyhow::Result;
use crate::core::{MemoryEngine, ProjectIndexer};
use crate::storage::{Context, Transaction};
use crate::hooks;
use chrono::{Duration, Utc};
use std::env;
use std::fs;
use std::path::PathBuf;

/// Initialize ARGUS (v2 - RTK-style)
pub async fn cmd_init_v2(global: bool, show: bool, uninstall: bool, no_rules: bool) -> Result<()> {
    if show {
        // Show installation status
        return hooks::show_status();
    }

    if uninstall {
        // Uninstall hooks
        let home = std::env::home_dir().ok_or_else(|| anyhow::anyhow!("Cannot determine home directory"))?;

        // Remove hooks
        hooks::uninstall_hooks()?;

        // Remove rules
        if !no_rules {
            let rules_path = home.join(".claude").join("rules").join("argus.md");
            if rules_path.exists() {
                fs::remove_file(&rules_path)?;
                crate::cli::output::success(&format!("Removed: {}", rules_path.display()));
            }
        }

        crate::cli::output::success("ARGUS uninstalled successfully");
        crate::cli::output::info("Run 'argus init -g' to reinstall");
        return Ok(());
    }

    // Regular init
    let home = std::env::home_dir().ok_or_else(|| anyhow::anyhow!("Cannot determine home directory"))?;

    // Create ~/.argus directory
    let argus_dir = home.join(".argus");
    fs::create_dir_all(&argus_dir)?;

    // Create index directory
    let index_dir = argus_dir.join("index");
    fs::create_dir_all(&index_dir)?;

    // Initialize database
    let _memory = MemoryEngine::new().await?;

    crate::cli::output::success(&format!("Created ARGUS data directory: {}", argus_dir.display()));

    // Install hooks if global flag is set
    if global {
        crate::cli::output::info("Installing hooks (RTK-style)...");
        hooks::install_hooks()?;
    } else {
        crate::cli::output::info("\n💡 Tip: Use 'argus init -g' to install Claude Code hooks");
    }

    // Inject rules to ~/.claude/rules/
    if !no_rules {
        let rules_dir = home.join(".claude").join("rules");
        fs::create_dir_all(&rules_dir)?;

        let rules_path = rules_dir.join("argus.md");

        let rules_content = r#"# ARGUS - Omniscient Memory Sentinel

> **Version:** 0.8.2 | **CLI:** `argus`

---

## 🎯 Purpose

ARGUS maintains semantic memory of all your Claude Code sessions.
**Always consult ARGUS before** exploring code or creating solutions.

## 🔧 Integration

ARGUS is installed as a CLI tool. Available commands:
- `argus recall "pattern"` - Search past transactions
- `argus remember "description"` - Save to memory
- `argus index` - Index current project
- `argus stats` - View statistics

## ✅ Mandatory Workflow

### Before ANY Explore or CreateTeam action:

```bash
# Step 1: Search ARGUS memory
argus recall "<what you're looking for>"

# Step 2: Review results
# Step 3: Proceed with action using context
```

### After ANY significant action:

```bash
# Save the result for future reference
argus remember "What you did and why"
```

## 🚫 Never

- Explore without checking ARGUS first
- CreateTeam without searching past solutions
- Ignore patterns found in memory
- Skip remembering important decisions

## 📊 Memory Location

All data stored in: `~/.argus/`
- Transactions: `~/.argus/memory.db`
- Index: `~/.argus/index/`

## 🔧 Installation

```bash
# Install globally
argus init -g

# Check status
argus init --show

# Uninstall
argus init -g --uninstall
```

---

*Auto-generated by ARGUS v0.8.2*
"#;

        fs::write(&rules_path, rules_content)?;
        crate::cli::output::success(&format!("Injected Claude Code rules: {}", rules_path.display()));
    } else {
        crate::cli::output::info("Skipped rules injection (--no-rules)");
    }

    crate::cli::output::success("ARGUS is ready! Use 'argus --help' to see available commands.");
    crate::cli::output::info("\nQuick start:");
    crate::cli::output::info("  argus remember \"Did something important\"");
    crate::cli::output::info("  argus recall \"something\"");

    Ok(())
}


/// Remember a transaction
pub async fn cmd_remember(description: String, tags: Option<String>, category: Option<String>) -> Result<()> {
    let memory = MemoryEngine::new().await?;

    // Build context
    let cwd = env::current_dir()?
        .to_str()
        .ok_or_else(|| anyhow::anyhow!("Invalid UTF-8 in path"))?
        .to_string();

    let context = Context {
        cwd: cwd.clone(),
        platform: std::env::consts::OS.to_string(),
        session_id: None,
        project_path: Some(cwd),
        git_branch: None,
        git_commit: None,
    };

    // Build transaction using builder pattern
    let mut tx = Transaction::user(description.clone(), context)
        .with_summary(description);

    if let Some(tags_str) = tags {
        let tag_list: Vec<String> = tags_str.split(',').map(|s| s.trim().to_string()).collect();
        tx = tx.with_tags(tag_list);
    }

    if let Some(cat) = category {
        tx = tx.with_category(cat);
    }

    // Store
    let id = memory.remember(tx).await?;

    success(&format!("Remembered as transaction #{}", id));

    Ok(())
}

/// Recall/search transactions
pub async fn cmd_recall(query: String, limit: usize, full: bool) -> Result<()> {
    let memory = MemoryEngine::new().await?;

    let results = memory.recall(&query, limit).await?;

    if results.is_empty() {
        print_info(&format!("No results found for: {}", cyan(&query)));
        return Ok(());
    }

    success(&format!("Found {} result(s) for: {}", results.len(), cyan(&query)));

    for tx in &results {
        print_transaction(tx, full);
    }

    Ok(())
}

/// List recent transactions
pub async fn cmd_list(limit: usize) -> Result<()> {
    let memory = MemoryEngine::new().await?;

    let results = memory.list(limit, 0).await?;

    if results.is_empty() {
        print_info("No transactions found.");
        return Ok(());
    }

    for tx in &results {
        print_transaction(tx, false);
    }

    Ok(())
}

/// Show a specific transaction
pub async fn cmd_show(id: i64) -> Result<()> {
    let memory = MemoryEngine::new().await?;

    match memory.get(id).await? {
        Some(tx) => {
            print_transaction(&tx, true);
            Ok(())
        }
        None => {
            error(&format!("Transaction #{} not found", id));
            Ok(())
        }
    }
}

/// Index current project
pub async fn cmd_index(_path: Option<PathBuf>, _force: bool) -> Result<()> {
    let indexer = ProjectIndexer::new().await?;
    let cwd = env::current_dir()?;

    print_info(&format!("Indexing: {}", cwd.display()));

    let stats = indexer.index(&cwd).await?;

    success(&format!(
        "Indexed {} files ({} bytes) in {}ms",
        green(&stats.files_indexed.to_string()),
        cyan(&format_size(stats.total_bytes)),
        yellow(&stats.duration_ms.to_string())
    ));

    Ok(())
}

/// Show statistics
pub async fn cmd_stats() -> Result<()> {
    let memory = MemoryEngine::new().await?;
    let stats = memory.stats().await?;

    println!("\n  📊 ARGUS Statistics\n");

    println!("  Transactions: {}", green(&stats.total_transactions.to_string()));
    println!("  Total Size:   {}", cyan(&format_size(stats.total_size_bytes as usize)));

    if let Some(oldest) = stats.oldest_transaction {
        let date_str = oldest.format("%Y-%m-%d %H:%M").to_string();
        println!("  Oldest:      {}", yellow(&date_str));
    }

    if let Some(newest) = stats.newest_transaction {
        let date_str = newest.format("%Y-%m-%d %H:%M").to_string();
        println!("  Newest:      {}", yellow(&date_str));
    }

    println!("\n  By Type:");
    for (ty, count) in &stats.transactions_by_type {
        println!("    {}: {}", ty, count);
    }

    println!();

    Ok(())
}

/// Configuration management
pub async fn cmd_config_get(key: String) -> Result<()> {
    let config = crate::cli::config::Config::load()?;

    match key.as_str() {
        "core.version" => println!("{}", config.core.version),
        "core.data_dir" => println!("{}", config.core.data_dir.as_deref().unwrap_or("~/.argus")),
        "memory.max_transactions" => println!("{}", config.memory.max_transactions),
        "memory.prune_after_days" => println!("{}", config.memory.prune_after_days),
        "recall.default_limit" => println!("{}", config.recall.default_limit),
        "recall.min_score" => println!("{}", config.recall.min_score),
        _ => {
            error(&format!("Unknown config key: {}", key));
            println!("Available keys:");
            println!("  core.version, core.data_dir");
            println!("  memory.max_transactions, memory.prune_after_days");
            println!("  recall.default_limit, recall.min_score");
        }
    }

    Ok(())
}

pub async fn cmd_config_set(key: String, value: String) -> Result<()> {
    let mut config = crate::cli::config::Config::load()?;

    match key.as_str() {
        "core.data_dir" => {
            config.core.data_dir = Some(value.clone());
            config.save()?;
            success(&format!("Set core.data_dir = {}", value));
        }
        "memory.max_transactions" => {
            let n = value.parse::<usize>()?;
            config.memory.max_transactions = n;
            config.save()?;
            success(&format!("Set memory.max_transactions = {}", n));
        }
        "memory.prune_after_days" => {
            let n = value.parse::<u64>()?;
            config.memory.prune_after_days = n;
            config.save()?;
            success(&format!("Set memory.prune_after_days = {}", n));
        }
        "recall.default_limit" => {
            let n = value.parse::<usize>()?;
            config.recall.default_limit = n;
            config.save()?;
            success(&format!("Set recall.default_limit = {}", n));
        }
        "recall.min_score" => {
            let n = value.parse::<f64>()?;
            config.recall.min_score = n;
            config.save()?;
            success(&format!("Set recall.min_score = {}", n));
        }
        _ => {
            error(&format!("Unknown config key: {}", key));
            return Ok(());
        }
    }

    Ok(())
}

pub async fn cmd_config_list() -> Result<()> {
    let config = crate::cli::config::Config::load()?;

    println!("\n  ⚙️  ARGUS Configuration\n");

    println!("\n  [core]");
    println!("    version: {}", config.core.version);
    if let Some(data_dir) = &config.core.data_dir {
        println!("    data_dir: {}", data_dir);
    }

    println!("\n  [memory]");
    println!("    max_transactions: {}", config.memory.max_transactions);
    println!("    prune_after_days: {}", config.memory.prune_after_days);

    println!("\n  [recall]");
    println!("    default_limit: {}", config.recall.default_limit);
    println!("    min_score: {}", config.recall.min_score);

    println!();

    Ok(())
}

/// Prune old transactions
pub async fn cmd_prune(before: String, dry_run: bool) -> Result<()> {
    let duration = parse_duration(&before)?;
    let cutoff = Utc::now() - duration;

    print_info(&format!("Pruning transactions older than: {}", cutoff.format("%Y-%m-%d %H:%M")));

    if dry_run {
        print_info("Dry run - no changes will be made");
        return Ok(());
    }

    let memory = MemoryEngine::new().await?;
    let count = memory.prune(cutoff).await?;

    success(&format!("Pruned {} transaction(s)", count));

    Ok(())
}

/// Reset all data
pub async fn cmd_reset(confirm: bool) -> Result<()> {
    if !confirm {
        crate::cli::output::warn("This will delete all ARGUS data!");
        crate::cli::output::warn("Run with --confirm to proceed.");
        return Ok(());
    }

    let home = std::env::home_dir().ok_or_else(|| anyhow::anyhow!("Cannot determine home directory"))?;
    let argus_dir = home.join(".argus");

    if argus_dir.exists() {
        fs::remove_dir_all(&argus_dir)?;
        success(&format!("Removed: {}", argus_dir.display()));
    } else {
        print_info("No ARGUS data found to remove.");
    }

    // Also remove rules
    let rules_path = home.join(".claude").join("rules").join("argus.md");
    if rules_path.exists() {
        fs::remove_file(&rules_path)?;
        success(&format!("Removed: {}", rules_path.display()));
    }

    print_info("Run 'argus init' to start fresh.");

    Ok(())
}

/// Delete a specific transaction
pub async fn cmd_delete(id: i64) -> Result<()> {
    let memory = MemoryEngine::new().await?;

    match memory.delete(id).await? {
        true => success(&format!("Deleted transaction #{}", id)),
        false => error(&format!("Transaction #{} not found", id)),
    }

    Ok(())
}

/// Search in indexed code
pub async fn cmd_search_code(query: String, limit: usize) -> Result<()> {
    let indexer = ProjectIndexer::new().await?;

    let results = indexer.search(&query, limit).await?;

    if results.is_empty() {
        print_info(&format!("No matches found for: {}", cyan(&query)));
        return Ok(());
    }

    success(&format!("Found {} match(es) for: {}", results.len(), cyan(&query)));

    for match_result in results {
        println!(
            "\n  {} {}:{}",
            green(&match_result.language),
            dim(&match_result.file_path),
            yellow(&match_result.line_number.to_string())
        );
        println!("  {}", dim(&match_result.snippet));
        println!("  score: {}", yellow(&format!("{:.2}", match_result.score)));
    }

    println!();
    Ok(())
}

/// Search in the database using FTS5 (more powerful than recall)
pub async fn cmd_search_db(query: String, limit: usize) -> Result<()> {
    let engine = crate::core::search::SearchEngine::new().await?;

    let results = engine.search(&query, limit).await?;

    if results.is_empty() {
        print_info(&format!("No results found for: {}", cyan(&query)));
        return Ok(());
    }

    success(&format!("Found {} result(s) for: {}", results.len(), cyan(&query)));

    for result in results {
        println!(
            "\n  {} {}",
            dim(&format!("#{}", result.transaction_id)),
            cyan(&result.prompt)
        );
        if let Some(summary) = &result.summary {
            println!("  {}", dim(&format!("({})", summary)));
        }
        println!("  {} {}", dim("at:"), dim(&result.created_at.format("%Y-%m-%d %H:%M").to_string()));
        println!("  score: {}", yellow(&format!("{:.2}", result.score)));
    }

    println!();
    Ok(())
}

/// Unindex a project
pub async fn cmd_unindex(project_path: PathBuf) -> Result<()> {
    let indexer = ProjectIndexer::new().await?;

    if !indexer.is_indexed(&project_path).await {
        print_info(&format!("Project not indexed: {}", project_path.display()));
        return Ok(());
    }

    indexer.unindex(&project_path).await?;
    success(&format!("Unindexed: {}", project_path.display()));

    Ok(())
}

/// Check if a project is indexed
pub async fn cmd_is_indexed(project_path: PathBuf) -> Result<()> {
    let indexer = ProjectIndexer::new().await?;

    if indexer.is_indexed(&project_path).await {
        success(&format!("Indexed: {}", project_path.display()));
    } else {
        print_info(&format!("Not indexed: {}", project_path.display()));
    }

    Ok(())
}

// Helper function to avoid conflict with info macro
fn print_info(msg: &str) {
    crate::cli::output::info(msg);
}

// Helper functions

fn print_transaction(tx: &Transaction, full: bool) {
    let id = tx.id.unwrap_or(0);
    let summary = tx.metadata.as_ref()
        .and_then(|m| m.summary.as_ref())
        .map(|s| s.as_str())
        .unwrap_or(&tx.prompt);

    println!(
        "\n  {} {}",
        dim(&format!("#{}", id)),
        summary
    );

    if let Some(created) = tx.created_at {
        let created_str = created.format("%Y-%m-%d %H:%M").to_string();
        println!(
            "  {} {}",
            dim("at:"),
            dim(&created_str)
        );
    }

    if full {
        if let Some(meta) = &tx.metadata {
            if !meta.tags.is_empty() {
                println!("  tags: {}", meta.tags.join(", "));
            }
            if let Some(intent) = &meta.intent {
                println!("  intent: {}", intent);
            }
        }
        println!("  prompt: {}", tx.prompt);
        if let Some(project) = &tx.context.project_path {
            println!("  project: {}", project);
        }
    }
}

fn format_size(bytes: usize) -> String {
    const KB: usize = 1024;
    const MB: usize = KB * 1024;
    const GB: usize = MB * 1024;

    if bytes >= GB {
        format!("{:.2} GB", bytes as f64 / GB as f64)
    } else if bytes >= MB {
        format!("{:.2} MB", bytes as f64 / MB as f64)
    } else if bytes >= KB {
        format!("{:.2} KB", bytes as f64 / KB as f64)
    } else {
        format!("{} B", bytes)
    }
}

fn parse_duration(s: &str) -> Result<Duration> {
    let s = s.to_lowercase();
    let (num, unit) = if s.ends_with('d') {
        (s.trim_end_matches('d'), "days")
    } else if s.ends_with('w') {
        (s.trim_end_matches('w'), "weeks")
    } else if s.ends_with('m') {
        (s.trim_end_matches('m'), "days") // months -> 30 days
    } else if s.ends_with('y') {
        (s.trim_end_matches('y'), "days") // years -> 365 days
    } else {
        return Err(anyhow::anyhow!("Invalid duration format. Use: 30d, 3m, 1y"));
    };

    let n: i64 = num.parse()
        .map_err(|_| anyhow::anyhow!("Invalid number: {}", num))?;

    let days = match unit {
        "days" => n,
        "weeks" => n * 7,
        _ => return Err(anyhow::anyhow!("Unknown unit: {}", unit)),
    };

    Ok(Duration::days(days))
}

/// Daemon: Start the ARGUS agent
pub async fn cmd_daemon_start(_background: bool, _foreground: bool) -> Result<()> {
    #[cfg(feature = "agent")]
    {
        use crate::agent::daemon;

        if daemon::is_daemon_running() {
            success("ARGUS Agent is already running");
            let status = daemon::daemon_status()?;
            if let Some(pid) = status.pid {
                println!("  PID: {}", pid);
            }
            if let Some(uptime) = status.uptime {
                println!("  Uptime: {}s", uptime);
            }
            return Ok(());
        }

        if foreground {
            // Run in foreground (for debugging)
            success("Starting ARGUS Agent in foreground...");
            let agent = daemon::AgentDaemon::new().await?;
            agent.run().await?;
        } else if background {
            // Run in background (detached, for auto-start from hooks)
            daemon::start_daemon_background()?;
            success("ARGUS Agent started in background");
        } else {
            // Default: interactive start (foreground with message)
            success("Starting ARGUS Agent...");
            println!("Press Ctrl+C to stop");
            let agent = daemon::AgentDaemon::new().await?;
            agent.run().await?;
        }

        Ok(())
    }

    #[cfg(not(feature = "agent"))]
    {
        error("Agent feature not enabled");
        error("Rebuild with: cargo build --release --features agent");
        Err(anyhow::anyhow!("Agent feature not enabled"))
    }
}

/// Daemon: Stop the ARGUS agent
pub async fn cmd_daemon_stop() -> Result<()> {
    #[cfg(feature = "agent")]
    {
        use crate::agent::daemon;

        if !daemon::is_daemon_running() {
            print_info("ARGUS Agent is not running");
            return Ok(());
        }

        daemon::stop_daemon()?;
        success("ARGUS Agent stopped");

        Ok(())
    }

    #[cfg(not(feature = "agent"))]
    {
        error("Agent feature not enabled");
        Err(anyhow::anyhow!("Agent feature not enabled"))
    }
}

/// Daemon: Check status
pub async fn cmd_daemon_status() -> Result<()> {
    #[cfg(feature = "agent")]
    {
        use crate::agent::daemon;

        let status = daemon::daemon_status()?;

        if status.running {
            success("ARGUS Agent is running");
            println!("\n  📊 Daemon Status:");
            if let Some(pid) = status.pid {
                println!("  PID: {}", pid);
            }
            if let Some(uptime) = status.uptime {
                let mins = uptime / 60;
                let secs = uptime % 60;
                println!("  Uptime: {}m {}s", mins, secs);
            }
            if let Some(version) = status.version {
                println!("  Version: {}", version);
            }
            println!("  IPC: {}", crate::agent::ipc::IpcTransport::for_platform()?.path());
        } else {
            print_info("ARGUS Agent is not running");
            print_info("Start it with: argus daemon start");
            print_info("Or enable auto-start with: argus install");
        }

        Ok(())
    }

    #[cfg(not(feature = "agent"))]
    {
        error("Agent feature not enabled");
        Err(anyhow::anyhow!("Agent feature not enabled"))
    }
}

/// Daemon: Ping the agent
pub async fn cmd_daemon_ping() -> Result<()> {
    #[cfg(feature = "agent")]
    {
        use crate::agent::ipc::IpcClient;

        match IpcClient::new() {
            Ok(client) => {
                if client.ping() {
                    success("ARGUS Agent is responding");
                    Ok(())
                } else {
                    error("ARGUS Agent did not respond");
                    Err(anyhow::anyhow!("Agent not responding"))
                }
            }
            Err(e) => {
                error(&format!("Failed to connect to agent: {}", e));
                Err(e)
            }
        }
    }

    #[cfg(not(feature = "agent"))]
    {
        error("Agent feature not enabled");
        Err(anyhow::anyhow!("Agent feature not enabled"))
    }
}
